Rubocop before rspec in precommit

diff --git a/.dev/pre-commit b/.dev/pre-commit
--- a/.dev/pre-commit
+++ b/.dev/pre-commit
@@ -7,19 +7,18 @@ backend_precommit() {
     if [ -n "$staged_backend_files" ]; then
         cd backend
 
+        rubocop
+        rubocop_result=$?
+        if [ $rubocop_result -ne 0 ]; then
+            echo "RuboCop failed for backend files. Aborting commit."
+            exit 1
+        fi
+
         echo "Running RSpec tests..."
         docker exec "$PROJECT_NAME-backend" bash -c "RAILS_ENV=test rspec"
         rspec_result=$?
         if [ $rspec_result -ne 0 ]; then
             echo "RSpec failed for backend files. Aborting commit."
-            exit 1
-        fi
-
-
-        rubocop
-        rubocop_result=$?
-        if [ $rubocop_result -ne 0 ]; then
-            echo "RuboCop failed for backend files. Aborting commit."
             exit 1
         fi
 
