Added frontend test to precommit

diff --git a/.dev/pre-commit b/.dev/pre-commit
--- a/.dev/pre-commit
+++ b/.dev/pre-commit
@@ -26,4 +26,19 @@ backend_precommit() {
     fi
 }
 
+frontend_precommit() {
+    staged_frontend_files=$(git diff --cached --name-only --diff-filter=ACM -- frontend/)
+    if [ -n "$staged_frontend_files" ]; then
+        cd frontend
+        docker exec -t "$PROJECT_NAME-frontend" sh -c "yarn test"
+        vitest_result=$?
+        if [ $vitest_result -ne 0 ]; then
+            echo "Vitest failed for frontend files. Aborting commit."
+            exit 1
+        fi
+        cd ..
+    fi
+}
+
 backend_precommit
+frontend_precommit
